// cspell:disable
export enum MessageType {
    JOIN = "JOIN",
    READY = "READY",
    START = "START",
    QUESTION = "QUESTION",
    ANSWER = "ANSWER",
    RESULTS = "RESULTS",
    ELIMINATED = "ELIMINATED",
    END = "END",
    ERROR = "ERROR",
    ROUND_START = "ROUND_START",
    ROUND_END = "ROUND_END",
    GAME_END = "GAME_END",
    PLAYER_LEAVE = "PLAYER_LEAVE",
    ANSWER_CONFIRMED = "ANSWER_CONFIRMED",
}